var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mie",
            "thu": "Jue",
            "fri": "Vie",
            "sat": "Sab",
            "jan": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "No implementado todavía",
        "to_date_view": "Clic para ver el dia de hoy",
        "i_undefined": "Indefinido",
        "allday_event": "Todo el día",
        "repeat_event": "Repetir evento",
        "time": "Fecha",
        "event": "Evento",
        "location": "Lugar",
        "participant": "Participantes",
        "get_data_exception": "Excepción cuando agarre información",
        "new_event": "Evento nuevo",
        "confirm_delete_event": "¿Confirma que desea borrar evento? ",
        "confrim_delete_event_or_all": "¿Desea todos o solo este evento? \r\nClic [OK] para borrar solo este evento, clic [Cancel] para borrar todos los eventos",
        "data_format_error": "¡Error en formato de información! ",
        "invalid_title": "Title del Evento no puede dejarse en blanco o contener ($<>)",
        "view_no_ready": "Vista no esta lista",
        "example": "ej., reunion en salon 107",
        "content": "Razón",
        "create_event": "Crear evento",
        "update_detail": "Detalles de Evento",
        "click_to_detail": "Ver detalles",
        "i_delete": "Borrar",
        "day_plural": "dias",
        "others": "Otros",
        "item": ""
    }
});
